### ISSUE TITLE
Can't enter the seed 

### ISSUE THREAD

**Issue by limpbrains** [jpph/seedsigner-distro#1]
I was trying to enter the seed to convert it to xpub, but right-middle buttons doesn't work, so I can't choose a word.
I'm running it in virtrualbox on mac
[seedsigner.webm](https://user-images.githubusercontent.com/155891/178100731-e9c4d5a2-1cf5-451d-9637-03a928108e4f.webm)

**Comment by jpph** [comment]
I have opened ticket upstream (the emulator project), issue is there too.
https://github.com/enteropositivo/seedsigner-emulator/issues/2

**Comment by jpph** [comment]
Has been corrected by enteropositivo upstream, working now. new build v2.01 out.
